### ISSUE TITLE
The tag 'cycle' seems not working

### ISSUE THREAD

**Issue by fungland** [michealbenedict/gulp-liquid#1]
An error "Liquid.SyntaxError: Unknown tag 'cycle'" occurred when I use tag 'cycle'.

**Comment by michealbenedict** [comment]
gulp-liquid uses [liquid-node](https://github.com/sirlantis/liquid-node/tree/master/src/liquid/tags) underneath. It seems that it doesn't support `cycle` tag.

Let me see what i can do about this, probably would have to move to using the liquid gem underneath.

**Comment by michealbenedict** [comment]
It seems to be a liquid-node issue. It would be better to file an issue with them.
